/** Set `VITE_STAGE_AGENT_NOTIFICATIONS=true` to preview the UI with demo data. */
export const isAgentNotificationsStagingEnabled = () =>
  import.meta.env.VITE_STAGE_AGENT_NOTIFICATIONS === "true";

export const STAGED_AGENT_NOTIFICATION_ID_PREFIX = "staged-";

export function isStagedAgentNotificationId(id: string): boolean {
  return id.startsWith(STAGED_AGENT_NOTIFICATION_ID_PREFIX);
}

export type AgentNotificationKind =
  | "skill"
  | "workflow"
  | "routine"
  | "responder";

export interface AgentNotification {
  id: string;
  kind: AgentNotificationKind;
  /** Display name for the recommended skill or automation. */
  name: string;
  /**
   * The exact message to send in a new conversation to (re)create this
   * skill or automation. Generated by the detection skill, not templated
   * client-side, so it can reference the specific work that was done.
   */
  prompt: string;
  /** ISO timestamp of when this was detected, used to order history. */
  createdAt: string;
}

/** Demo agent notifications used only when staging is enabled. */
export const STAGED_AGENT_NOTIFICATIONS: AgentNotification[] = [
  {
    id: "staged-skill-standup-digest",
    kind: "skill",
    name: "Standup digest helper",
    prompt:
      'Save a reusable skill named "Standup digest helper" that gathers each ' +
      "teammate's merged PRs, open PRs, and blocked items from the last 24 " +
      "hours and formats them as a short standup update.",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "staged-workflow-release-notes",
    kind: "workflow",
    name: "Release notes drafter",
    prompt:
      'Create a workflow named "Release notes drafter" that runs when a ' +
      "release tag is pushed: summarize the merged PRs since the last tag " +
      "into grouped release notes (features, fixes, chores) and open a PR " +
      "updating CHANGELOG.md.",
    createdAt: "2026-01-01T00:00:01.000Z",
  },
  {
    id: "staged-routine-dependency-audit",
    kind: "routine",
    name: "Weekly dependency audit",
    prompt:
      'Create a routine named "Weekly dependency audit" that runs every ' +
      "Monday at 9am: check for outdated or vulnerable dependencies and " +
      "open a PR bumping the safe ones, with a summary comment for the rest.",
    createdAt: "2026-01-01T00:00:02.000Z",
  },
  {
    id: "staged-responder-ci-watchdog",
    kind: "responder",
    name: "CI failure watchdog",
    prompt:
      'Create a responder named "CI failure watchdog" that triggers on a ' +
      "failed CI run: diagnose the failing job's logs and post a summary " +
      "of the likely cause as a PR comment.",
    createdAt: "2026-01-01T00:00:03.000Z",
  },
];
