"""BDD test implementations for skills loading scenarios.

Implements pytest-bdd test functions for:
- skills_loading.feature
- skills_context_isolation.feature
- skills_gating.feature
- skills_error_handling.feature

Run with: pytest tests/bdd/features/agent/test_skills_scenarios.py -v
"""

from __future__ import annotations

from pytest_bdd import scenarios

# Import step definitions directly into module namespace so pytest-bdd can discover them
# This pattern matches test_agent_execution.py which works correctly
from tests.bdd.steps.skills_steps import *  # noqa: F401, F403

# Load scenarios from feature files
scenarios('skills_loading.feature')
scenarios('skills_context_isolation.feature')
scenarios('skills_gating.feature')
scenarios('skills_error_handling.feature')


# These test functions are auto-generated by pytest-bdd from the .feature files
# No manual implementation needed here - the step definitions in tests/bdd/steps/skills_steps.py
# handle the Given/When/Then execution.
