selected_ids = [
    "pvlib__pvlib-python-1707",
      "pylint-dev__astroid-1614",
      "sqlfluff__sqlfluff-884",
      "pydicom__pydicom-1192",
      "pvlib__pvlib-python-1589",
      "pylint-dev__astroid-1616",
      "sqlfluff__sqlfluff-905",
      "pydicom__pydicom-938",
      "marshmallow-code__marshmallow-1343",
      "sqlfluff__sqlfluff-2419",
      "pvlib__pvlib-python-1854",
      "pylint-dev__astroid-1719",
      "marshmallow-code__marshmallow-1164",
      "marshmallow-code__marshmallow-1252",
      "pydicom__pydicom-965",
      "pylint-dev__astroid-1903",
      "pydicom__pydicom-1694",
      "pylint-dev__astroid-1196",
      "pydicom__pydicom-1256",
      "pydicom__pydicom-1228",
      "pvlib__pvlib-python-1738",
      "pvlib__pvlib-python-1349",
      "pylint-dev__astroid-1962",
      "pylint-dev__astroid-1959",
      "marshmallow-code__marshmallow-1810",
]
