name: Publish to ECR

on:
  push:
    tags:
      - "*"

env:
  AWS_REGION: eu-central-1
  DOCKER_REPOSITORY: 653306034207.dkr.ecr.eu-central-1.amazonaws.com/b1
  APP_NAME: openhands

jobs:
  publish:
    name: Build and push to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.B1_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.B1_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          docker build . -f containers/app/Dockerfile \
            -t "${DOCKER_REPOSITORY}/${APP_NAME}:${VERSION}" \
            --build-arg BUILD_VERSION="${VERSION}" \
            --build-arg BUILD_DATE="$(date)" \
            --build-arg BUILD_NAME="${APP_NAME}" \
            --build-arg BUILD_IMAGE="${DOCKER_REPOSITORY}/${APP_NAME}"
          docker push "${DOCKER_REPOSITORY}/${APP_NAME}:${VERSION}"
        timeout-minutes: 30
